service: UserAuthApi
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 2048 # Lambda memory size to ensure we have faster boot time
  stage: dev # set the stage as your environment dev, prod, etc
  timeout: 10
  region: us-east-1

functions:
  userAuth:
    handler: handler.userAuth
    events:
      - http: ANY /{proxy+}
      - http: ANY /